### ISSUE TITLE
[req] Provide usage examples of scheduling

### ISSUE THREAD

**Issue by jarodium** [thewebguy/bufferapp-php#4]
Hello 

Can you provide example of the flow of scheduling of posts?

Best regards

**Comment by dcblogdev** [comment]
You would have a schedule setup on buffer this wrapper can be used to post to your buffer queue, buffer would then put the post into the schedule you've already got setup.

Ah just noticed in the API there is the option for scheduled_at https://buffer.com/developers/api/updates#updatescreate

timestamp or ISO 8601 formatted date-time 
A date describing when the update should be posted. Overrides any top or now parameter. When using ISO 8601 format, if no UTC offset is specified, UTC is assumed.

along the lines of:

```
$buffer->go('/updates/create', array(
'text' => 'My first status update from bufferapp-php worked!', 
'profile_ids[]' => $profile->id,
'scheduled_at' => date(DATE_ISO8601, strtotime('2018-01-10 23:21:46'))
));
```

**Comment by jarodium** [comment]
Thank you
